### ISSUE TITLE
ошибка

### ISSUE THREAD

**Issue by K-Faktor** [T-Maxxx/iw3linker_vs#3]
С чем это связано?
![Аннотация 2020-06-12 153225](https://user-images.githubusercontent.com/27491186/84494022-328dad00-acc2-11ea-8270-fab3b32b12de.png)

**Comment by T-Maxxx** [comment]
VirtualAlloc - функция по выделению оперативной памяти. Судя по тексту ошибки, , не удалось выделить запрошенный кусок памяти, причем, тебе попалась ошибка в коде самого компоновщика, а не в моем. Спасибо за фидбек, посмотрю.

**Comment by T-Maxxx** [comment]
@K-Faktor Отпишись, если ошибка исправлена https://github.com/T-Maxxx/iw3linker_vs/releases

**Comment by K-Faktor** [comment]
> @K-Faktor Отпишись, если ошибка исправлена https://github.com/T-Maxxx/iw3linker_vs/releases

Только что проверил, компиляция прошла без ошибок. количество интеграции моделей 105 штук
